### ISSUE TITLE
Move packages to their respective repo's

### ISSUE THREAD

**Issue by robbevp** [accentor/flake#5]
Since everyone currently working on Accentor is using nix, i would like to have a devshell inside the packages directly.

While nix should remain opt-in for everyone using/working on Accentor, i don't think a few extra files in the root dir would be a problem.

How i see this:
The api/web repo get:
- A flake that exposes a devshell and default packages.
- a gemset.nix/yarn.nix file
- a github action to keep this gemset.nix/yarn.nix up to date after a dependabot update (or when someone not using nix changes a dependency)

This repo keeps all the code to easily deploy a Accentor with nixOS.

@chvp @rien thoughts?

**Comment by rien** [comment]
It makes sense to have the nix packaging instructions in the repository of the package itself indeed :+1:

**Comment by chvp** [comment]
Definitely fine by me, it would make my life deploying the latest commit to our server much easier.
